// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: perfdata.proto
#ifndef GRPC_perfdata_2eproto__INCLUDED
#define GRPC_perfdata_2eproto__INCLUDED

#include "perfdata.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace rocksdb {

class PerfDataService final {
 public:
  static constexpr char const* service_full_name() {
    return "rocksdb.PerfDataService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status SendPerfData(::grpc::ClientContext* context, const ::rocksdb::PerfDataRequest& request, ::rocksdb::PerfDataResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rocksdb::PerfDataResponse>> AsyncSendPerfData(::grpc::ClientContext* context, const ::rocksdb::PerfDataRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rocksdb::PerfDataResponse>>(AsyncSendPerfDataRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rocksdb::PerfDataResponse>> PrepareAsyncSendPerfData(::grpc::ClientContext* context, const ::rocksdb::PerfDataRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rocksdb::PerfDataResponse>>(PrepareAsyncSendPerfDataRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void SendPerfData(::grpc::ClientContext* context, const ::rocksdb::PerfDataRequest* request, ::rocksdb::PerfDataResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SendPerfData(::grpc::ClientContext* context, const ::rocksdb::PerfDataRequest* request, ::rocksdb::PerfDataResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::rocksdb::PerfDataResponse>* AsyncSendPerfDataRaw(::grpc::ClientContext* context, const ::rocksdb::PerfDataRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::rocksdb::PerfDataResponse>* PrepareAsyncSendPerfDataRaw(::grpc::ClientContext* context, const ::rocksdb::PerfDataRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status SendPerfData(::grpc::ClientContext* context, const ::rocksdb::PerfDataRequest& request, ::rocksdb::PerfDataResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rocksdb::PerfDataResponse>> AsyncSendPerfData(::grpc::ClientContext* context, const ::rocksdb::PerfDataRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rocksdb::PerfDataResponse>>(AsyncSendPerfDataRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rocksdb::PerfDataResponse>> PrepareAsyncSendPerfData(::grpc::ClientContext* context, const ::rocksdb::PerfDataRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rocksdb::PerfDataResponse>>(PrepareAsyncSendPerfDataRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void SendPerfData(::grpc::ClientContext* context, const ::rocksdb::PerfDataRequest* request, ::rocksdb::PerfDataResponse* response, std::function<void(::grpc::Status)>) override;
      void SendPerfData(::grpc::ClientContext* context, const ::rocksdb::PerfDataRequest* request, ::rocksdb::PerfDataResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::rocksdb::PerfDataResponse>* AsyncSendPerfDataRaw(::grpc::ClientContext* context, const ::rocksdb::PerfDataRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::rocksdb::PerfDataResponse>* PrepareAsyncSendPerfDataRaw(::grpc::ClientContext* context, const ::rocksdb::PerfDataRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_SendPerfData_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status SendPerfData(::grpc::ServerContext* context, const ::rocksdb::PerfDataRequest* request, ::rocksdb::PerfDataResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_SendPerfData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SendPerfData() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_SendPerfData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendPerfData(::grpc::ServerContext* /*context*/, const ::rocksdb::PerfDataRequest* /*request*/, ::rocksdb::PerfDataResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSendPerfData(::grpc::ServerContext* context, ::rocksdb::PerfDataRequest* request, ::grpc::ServerAsyncResponseWriter< ::rocksdb::PerfDataResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_SendPerfData<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_SendPerfData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SendPerfData() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::rocksdb::PerfDataRequest, ::rocksdb::PerfDataResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::rocksdb::PerfDataRequest* request, ::rocksdb::PerfDataResponse* response) { return this->SendPerfData(context, request, response); }));}
    void SetMessageAllocatorFor_SendPerfData(
        ::grpc::MessageAllocator< ::rocksdb::PerfDataRequest, ::rocksdb::PerfDataResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::rocksdb::PerfDataRequest, ::rocksdb::PerfDataResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_SendPerfData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendPerfData(::grpc::ServerContext* /*context*/, const ::rocksdb::PerfDataRequest* /*request*/, ::rocksdb::PerfDataResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SendPerfData(
      ::grpc::CallbackServerContext* /*context*/, const ::rocksdb::PerfDataRequest* /*request*/, ::rocksdb::PerfDataResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_SendPerfData<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_SendPerfData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SendPerfData() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_SendPerfData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendPerfData(::grpc::ServerContext* /*context*/, const ::rocksdb::PerfDataRequest* /*request*/, ::rocksdb::PerfDataResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_SendPerfData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SendPerfData() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_SendPerfData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendPerfData(::grpc::ServerContext* /*context*/, const ::rocksdb::PerfDataRequest* /*request*/, ::rocksdb::PerfDataResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSendPerfData(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SendPerfData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SendPerfData() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SendPerfData(context, request, response); }));
    }
    ~WithRawCallbackMethod_SendPerfData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendPerfData(::grpc::ServerContext* /*context*/, const ::rocksdb::PerfDataRequest* /*request*/, ::rocksdb::PerfDataResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SendPerfData(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SendPerfData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SendPerfData() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::rocksdb::PerfDataRequest, ::rocksdb::PerfDataResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::rocksdb::PerfDataRequest, ::rocksdb::PerfDataResponse>* streamer) {
                       return this->StreamedSendPerfData(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SendPerfData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SendPerfData(::grpc::ServerContext* /*context*/, const ::rocksdb::PerfDataRequest* /*request*/, ::rocksdb::PerfDataResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSendPerfData(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::rocksdb::PerfDataRequest,::rocksdb::PerfDataResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_SendPerfData<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_SendPerfData<Service > StreamedService;
};

}  // namespace rocksdb


#endif  // GRPC_perfdata_2eproto__INCLUDED
